name: Deploy

on:
  push:
    branches: [main]
#  release:
#    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest

    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 25.x
      - run: corepack enable
      - run: yarn install --immutable
      - run: yarn ci:build
      - run: yarn ci:test
        env:
          LISTEN_PORT: 3000
          DATABASE_URL: "postgres://postgres:postgres@postgres:5432/postgres-dummy"
          TEST_DB_URL: "postgres://postgres:postgres@postgres:5432/postgres"
          ALLOWED_ORIGINS: http://localhost
          JWT_SECRET: thisisnotarealsecretthisisfortestingonlydonotuseinprod
          ACCESS_TOKEN_DURATION: 5
          REFRESH_TOKEN_DURATION: 2592000
          REFRESH_TOKEN_SIZE: 32
          REGISTRATION_PASSWORD: notarealpassword

      - name: Copy files to VPS
        env:
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
          VPS_IP: ${{ secrets.VPS_IP }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H $VPS_IP >> ~/.ssh/known_hosts
          rsync -avz --delete ./client/build/ github@$VPS_IP:/var/openselves/client/
          rsync -avz --delete ./server/dist/ github@$VPS_IP:/var/openselves/server/
