name: Deploy www

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v6
        with:
          node-version: 26.x
      - run: corepack enable
      - uses: actions/checkout@v6
      - uses: actions/cache@v5
        with:
          key: yarn
          path: ~/.yarn
      - run: yarn install --immutable
        env:
          PUPPETEER_SKIP_DOWNLOAD: true

      # This also calls `yarn build`
      - run: yarn lint

      - name: Copy files to VPS
        env:
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
          VPS_IP: ${{ secrets.VPS_IP }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H $VPS_IP >> ~/.ssh/known_hosts
          rsync -avz --delete ./www/build/ github@$VPS_IP:/var/openselves/www/
